version: '3.3'

services:
  webservice:
    container_name: dart-games
    image: nginx:latest
    ports:
    - "80:80"
    volumes:
    - ../dart-app/src/app/:/usr/share/nginx/html:ro
    restart: unless-stopped
